# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

ModuleNotFoundError: No module named 'nbformat'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
!numpy --version

'numpy' is not recognized as an internal or external command,
operable program or batch file.


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
arr=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
print(np.size(arr))

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
!%run `python -c "import numpy; numpy.info(numpy.add)

'%run' is not recognized as an internal or external command,
operable program or batch file.


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [21]:
arr=np.arange(50)
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
arr=np.arange(0,9)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
arr=np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [43]:
arr=np.random.randint(1,3,size=(3,3,3))
arr

array([[[1, 2, 2],
        [1, 2, 2],
        [2, 1, 2]],

       [[1, 1, 2],
        [2, 2, 2],
        [1, 1, 1]],

       [[2, 1, 2],
        [1, 2, 2],
        [1, 2, 2]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [50]:
arr=np.random.random((10,10))
# print(arr)
print(f"Maximum Value: {arr.max()}")
print(f"Minimum Value: {arr.min()}")

Maximum Value: 0.9870830837821194
Minimum Value: 0.0022338915383949276


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr=np

array([72, 53, 56, 56, 66, 61, 73, 40,  9, 22, 15, 38, 50, 67, 31, 49, 59,
       78, 37, 92, 85, 62, 23, 22, 13, 10, 63,  2, 89, 27])

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [73]:
arr=np.ones((10,9))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [84]:
arr=np.ones((5,5))
# arr=np.pad(arr,pad_width=1,mode='constant', constant_values=0)
# arr[:,[0,-1]]=0
# arr[[0,-1],:]=0
arr = np.ones((7,7))
arr[3:-3, 3:-3] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [96]:
0*np.nan # nan
np.nan==np.nan #False
np.inf>np.nan  # False
np.nan-np.nan #nan
np.nan in set([np.nan]) #This is True as there hash set is same
0.3==3*0.1 #It is FALSE can be found correct by np.isclose()


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [114]:
arr=np.ones((5,5))
diagonal=np.arange(4)
arr=np.diag(1+diagonal,k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [117]:
arr=np.ones((8,8))
arr
#First select odd row even columns
arr[1::2,0::2]=0
#Second Select even row odd column
arr[0::2,1::2]=0
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [131]:
arr=np.ones((6,7,8))
arr=np.unravel_index(99,arr.shape)
arr

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [2]:
import numpy as np
arr=np.array([[1,0],[0,1]])
print(arr)
np.tile(arr,(4,4))

[[1 0]
 [0 1]]


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [6]:
arr=np.random.random((5,5))
print(arr)
arr = (arr - arr.mean()) / arr.std()
print(arr)

[[0.53751872 0.50357057 0.09331333 0.2615241  0.76420818]
 [0.1155942  0.19023004 0.29742859 0.56699301 0.38091774]
 [0.77273919 0.24866059 0.95695001 0.9046637  0.19174959]
 [0.64265023 0.69905129 0.75604848 0.78434341 0.55960693]
 [0.81048399 0.19540059 0.56685599 0.91362289 0.96140251]]
[[-0.03416149 -0.15620636 -1.63109689 -1.02637271  0.78079583]
 [-1.55099631 -1.28267761 -0.89729471  0.07179972 -0.597148  ]
 [ 0.81146515 -1.07261755  1.47371012  1.28573882 -1.27721477]
 [ 0.34379034  0.54655431  0.75146141  0.85318276  0.04524651]
 [ 0.94715914 -1.26408928  0.07130714  1.31794744  1.48971701]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [13]:
color_dtype=np.dtype([
    ('r',np.uint8),
    ('g',np.uint8),
    ('b',np.uint8),
    ('a',np.uint8)
])
# color_dtype=np.dtype([['r','g','b','a'],np.uint8]) This generates error above is only correct option through which each label have their data type defined


arr=np.array([(23,34,355,233),(64,46,89,76)],dtype=color_dtype)
arr

C:\Users\Lakshya Singh\AppData\Local\Temp\ipykernel_11704\2475809615.py:10: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 355 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr=np.array([(23,34,355,233),(64,46,89,76)],dtype=color_dtype)


array([(23, 34, 99, 233), (64, 46, 89,  76)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
A=np.random.random((5,3))
B=np.random.random((3,2))
c=np.dot(A,B)
print(c)
print(A@B)
print(c==A@B)

[[0.52095096 0.32677025]
 [0.24436435 0.36166847]
 [0.233671   0.15507465]
 [0.80172921 1.02516661]
 [0.47639842 0.45311445]]
[[0.52095096 0.32677025]
 [0.24436435 0.36166847]
 [0.233671   0.15507465]
 [0.80172921 1.02516661]
 [0.47639842 0.45311445]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr=np.random.randint(1,10,(1,5))
arr
arr=[arr-2*arr for arr<3 or arr>8]

SyntaxError: invalid syntax (237056150.py, line 3)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [6]:
##rd one is illegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [10]:
import numpy as np
print(f"{np.array(0)//np.array(0)} {np.array([np.nan]).astype(float)}")

0 [nan]


C:\Users\Lakshya Singh\AppData\Local\Temp\ipykernel_20884\1092851078.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(f"{np.array(0)//np.array(0)} {np.array([np.nan]).astype(float)}")


#### 29. How to round away from zero a float array ? (★☆☆)

In [17]:
arr=np.arange(5)
print(arr)
np.ceil(arr)

[0 1 2 3 4]


array([0., 1., 2., 3., 4.])

#### 30. How to find common values between two arrays? (★☆☆)

In [21]:
arr=np.arange(1,10)
arr1=np.arange(5)
arr2=np.intersect1d(arr,arr1)
arr2

array([1, 2, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [22]:
#We can use np setter fix etc   

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [14]:
np.sqrt(-1)
np.emath.sqrt(-1)

C:\Users\Lakshya Singh\AppData\Local\Temp\ipykernel_20884\2597603586.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [37]:
now=np.datetime64('now')
yesterday=now-timedelta64(1,'D')
tomorrow=now+timedelta64(1,'D')
now
yesterday
tomorrow

numpy.datetime64('2026-01-09T16:22:21')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [38]:
np.arange(
    np.datetime64('2016-07-01'),
    np.datetime64('2016-08-01'),
    np.timedelta64(1, 'D')
)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [42]:
A=np.array(2.0)
B=np.array(3.0)
np.add(A, B, out=A)        # A = A + B
np.negative(A, out=A)     # A = -(A + B)
np.multiply(A, B, out=A)  # A = (A + B) * (-B)
np.divide(A, 2, out=A)    # A = ((A + B) * (-B)) / 2

array(-7.5)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [61]:
arr=np.random.random((1,5))
print(arr)
arr.dtype=int64
arr

[[0.85468763 0.37910387 0.26227929 0.400524   0.38083353]]


array([[4605873561356662276, 4600500948040809822, 4598396423531521544,
        4600886818935344260, 4600532106944121270]], dtype=int64)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [66]:
arr=np.random.randint(0,5,(5,5))
arr

array([[1, 0, 2, 0, 4],
       [0, 0, 4, 2, 4],
       [1, 0, 2, 4, 3],
       [2, 1, 2, 2, 0],
       [2, 0, 4, 0, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [67]:
def gen():
    for i in range(10):
        yield i
arr=np.fromiter(gen(),dtype=int,count=10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [84]:
arr=np.linspace(0,1,12)[1:-1]
arr
#This creates a equal distance partition between two points

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [91]:
arr=np.random.random(size=10)
print(arr)
arr.sort()
print(arr)

[0.13408507 0.4658753  0.39241222 0.84507479 0.57492459 0.9179808
 0.69758504 0.93675144 0.21323583 0.13134678]
[0.13134678 0.13408507 0.21323583 0.39241222 0.4658753  0.57492459
 0.69758504 0.84507479 0.9179808  0.93675144]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [108]:
arr=np.arange(10)
arr1=np.add.reduce(arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [98]:
# 42. Consider twoa=np.arange(3)
a=np.arange(3)
b=np.arange(3)
np.allclose(a,b)
np.array_equal(a,b)
#This both check array equality based on value and calculation

True

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr.flags.writeable=False
arr[0]=10

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [117]:
arr=np.random.random((10,2))
x=arr[:,0]
y=arr[:,1]
r=np.sqrt(x**2+y**2)
theta=np.arctan2(y,x)
arr
polar = np.column_stack((r, theta))
polar

array([[0.08852936, 1.46477518],
       [0.74894008, 1.09754734],
       [0.66181638, 1.36170608],
       [0.94148056, 0.79561007],
       [0.4729307 , 0.31341249],
       [0.53090347, 0.86402795],
       [0.21867911, 0.00258822],
       [1.00244878, 0.46580495],
       [0.26794338, 0.37894161],
       [0.81209965, 0.27067943]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [124]:
arr=np.random.random(size=10)
print(arr.max)
arr[arr.argmax()]=0
arr

<built-in method max of numpy.ndarray object at 0x000001C4CA1E70F0>


array([0.46284444, 0.67178571, 0.44396786, 0.        , 0.64031585,
       0.54015516, 0.02639495, 0.05128704, 0.74484403, 0.10661564])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [135]:
x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 10)
X, Y = np.meshgrid(x, y)
# Z = np.zeros(X.size, dtype=[('x',float),('y',float)])
# Z['x'], Z['y'] = X.ravel(), Y.ravel()
Z = np.zeros(X.size, dtype=[('x',float),('y',float)])
Z['x'] = X.ravel()
Z['y'] = Y.ravel()
Z

array([(0.        , 0.        ), (0.11111111, 0.        ),
       (0.22222222, 0.        ), (0.33333333, 0.        ),
       (0.44444444, 0.        ), (0.55555556, 0.        ),
       (0.66666667, 0.        ), (0.77777778, 0.        ),
       (0.88888889, 0.        ), (1.        , 0.        ),
       (0.        , 0.11111111), (0.11111111, 0.11111111),
       (0.22222222, 0.11111111), (0.33333333, 0.11111111),
       (0.44444444, 0.11111111), (0.55555556, 0.11111111),
       (0.66666667, 0.11111111), (0.77777778, 0.11111111),
       (0.88888889, 0.11111111), (1.        , 0.11111111),
       (0.        , 0.22222222), (0.11111111, 0.22222222),
       (0.22222222, 0.22222222), (0.33333333, 0.22222222),
       (0.44444444, 0.22222222), (0.55555556, 0.22222222),
       (0.66666667, 0.22222222), (0.77777778, 0.22222222),
       (0.88888889, 0.22222222), (1.        , 0.22222222),
       (0.        , 0.33333333), (0.11111111, 0.33333333),
       (0.22222222, 0.33333333), (0.33333333, 0.33333333

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [136]:
X = np.array([1, 2, 3])
Y = np.array([4, 5])

C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(dtype, info.min, info.max)

-2147483648 2147483647
-1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [147]:
# arr[:]
np.set_printoptions(threshold=np.inf)

Z = np.arange(100)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [150]:
Z = np.array([1, 3, 7, 10])
x = 6

closest = Z[np.abs(Z - x).argmin()]
print(closest)
# Z - x → distance from x

# np.abs(...) → absolute distance

# .argmin() → index of smallest distance

# Z[...] → fetch the actual value

7


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)